# Generated by Django 4.2.11 on 2024-04-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group_management', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(default='profile_photos/default.jpg', max_length=255, upload_to='profile_photos/'),
        ),
    ]
