# Generated by Django 5.0.2 on 2024-04-03 05:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_group_management', '0002_remove_user_name_user_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectiondata',
            fields=[
                ('meta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publish_status', models.SmallIntegerField(choices=[(1, 'Personal'), (2, 'Group'), (3, 'Organization'), (4, 'Public')], default=1)),
                ('database_name', models.CharField(max_length=50)),
                ('connection_details', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_owner', to=settings.AUTH_USER_MODEL)),
                ('publish_to_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_group_management.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tabledata',
            fields=[
                ('table_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('test_pass', models.IntegerField(default=0)),
                ('test_fail', models.IntegerField(default=0)),
                ('test_abort', models.IntegerField(default=0)),
                ('inserted_data', models.JSONField(null=True)),
                ('deleted_data', models.JSONField(null=True)),
                ('scheduled', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connectiondata')),
            ],
        ),
        migrations.CreateModel(
            name='Matric',
            fields=[
                ('matric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_count', models.IntegerField(default=0)),
                ('col_count', models.IntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('matric_value', models.JSONField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.tabledata')),
            ],
        ),
        migrations.CreateModel(
            name='Columndata',
            fields=[
                ('column_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('datatype', models.CharField(max_length=30)),
                ('last_data', models.JSONField(null=True)),
                ('test_pass', models.IntegerField(default=0)),
                ('test_fail', models.IntegerField(default=0)),
                ('test_abort', models.IntegerField(default=0)),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.tabledata')),
            ],
        ),
    ]
