# Generated by Django 5.0.2 on 2024-04-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matric',
            new_name='Metric',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='matric_value',
            new_name='metric_value',
        ),
        migrations.AddField(
            model_name='connectiondata',
            name='database_type',
            field=models.CharField(default='Postgres', max_length=50),
            preserve_default=False,
        ),
    ]
