# Generated by Django 5.0.2 on 2024-04-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_rename_matric_metric_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columndata',
            old_name='tables',
            new_name='table',
        ),
    ]
