# Generated by Django 5.0.2 on 2024-04-10 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_rename_tables_columndata_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabledata',
            old_name='description',
            new_name='dag_run_id',
        ),
        migrations.AlterField(
            model_name='columndata',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='connector.tabledata'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='connector.tabledata'),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='connector.connectiondata'),
        ),
    ]
