# Generated by Django 5.0.2 on 2024-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_rename_description_tabledata_dag_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Success'), (4, 'Failed')], default=1),
        ),
    ]
