# Generated by Django 4.2.11 on 2024-04-15 09:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connector', '0005_tabledata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('test_purpose', models.CharField(max_length=100)),
                ('test_purpose_value', models.JSONField(blank=True, null=True)),
                ('test_type', models.SmallIntegerField(choices=[(1, 'Table'), (2, 'Column')], default=1)),
                ('dag_run_id', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Queued'), (2, 'Running'), (3, 'Success'), (4, 'Failed')], default=1)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_column', to='connector.columndata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_owner', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_table', to='connector.tabledata')),
            ],
        ),
    ]
