# Generated by Django 4.2.11 on 2024-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_test_result_alter_test_test_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='dag_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='etl_abort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='etl_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='etl_pass',
            field=models.IntegerField(default=0),
        ),
    ]
